# Generated by Django 5.0.2 on 2024-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('useremail', models.EmailField(max_length=255)),
                ('phonenumber', models.IntegerField()),
                ('message', models.TextField()),
                ('myimage', models.ImageField(blank=True, null=True, upload_to='userprofile')),
            ],
        ),
    ]
